### ISSUE TITLE
SN stable under substitution

### ISSUE THREAD

**Issue by gallais** [andreasabel/strong-normalization#12]
The proof that [inductive SN is stable under substitution](https://github.com/andreasabel/strong-normalization/blob/0c9b2a623953229024ffc65eaa9524acf66c65d2/sn-proof/sn-proof.tex#L944) is not trivial. In the application case for `SNe`, how are we supposed to combine the two IH?

It seems the lemma that comes right after this one is precisely the missing piece. But it is proven as a corollary.

By the way this corollary alone is pretty powerful: we can prove completeness of `SN` immediately after obtaining it (and without having to distinguish on `C[x]` vs. `C[(\x.b)t]` as in the proof of Th. 3.14). Edit: or even more than that: prove `SN t` by simple induction on `t` as soon as you have this corollary. I guess this means that lemma needs to be scrapped.

**Comment by pientka** [comment]
> On Feb 14, 2018, at 5:42 PM, G. Allais <notifications@github.com> wrote:
> 
> The proof that inductive SN is stable under substitution <https://github.com/andreasabel/strong-normalization/blob/0c9b2a623953229024ffc65eaa9524acf66c65d2/sn-proof/sn-proof.tex#L944> is not trivial. In the application case for SNe, how are we supposed to combine the two IH?
> 
> It seems the lemma that comes right after this one is precisely the missing piece.But it is proven as a corollary.
> 

I am guessing you mean by “corollary” the lemma 3.9 [SN is closed under application]. One should prove lemma 3.8 and 3.9 together — as you correctly observe there is a mutual dependency; and one should spell out the proof of 3.8. I haven’t had time to write it out — if you want to help, you are welcome ;-)

> By the way this corollary alone is pretty powerful: we can prove completeness of SN immediately after obtaining it (and without having to distinguish on C[x] vs. C[(\x.b)t] as in the proof of Th. 3.14).
> 
> 

This is correct. Thanks for pointing it out. Feel free to make more suggestions or fix some things in the proofs. This document is still work in progress and there are many things that should be streamlined and slightly re-arranged to make the proof structure clearer. 

- Brigitte

**Comment by gallais** [comment]
Looking at the APLAS paper, it looks like the statement needs to be
different: SN is stable under substitution *for strongly neutrals*.

Which makes sense: under this type of substitution SNe should be
stable which means the proof will be easy!

http://www.cse.chalmers.se/~abela/guarded-normalization/SN.html#8314

**Comment by pientka** [comment]
Yes, this is correct. Feel free to fix it in the file as well.
